name: Check Quiz Answers

on:
  pull_request:
    paths:
      - 'quiz_answers_*.txt'

jobs:
  check-answers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find participant answer file
        run: |
          ANSWER_FILE=$(find . -name "quiz_answers_*.txt" | head -n 1)
          if [ -z "$ANSWER_FILE" ]; then
            echo "No answer file found!"
            exit 1
          fi
          echo "Found answer file: $ANSWER_FILE"

      - name: Extract Participant Answers
        run: |
          # Extract lines with marked answers, trim whitespaces, and format consistently
          grep -o '^[0-9]*: \[x\].*' "$ANSWER_FILE" | sed 's/^\([0-9]*\): \[x\] \(.*\)/\1: \2/' | tr -d '\r' | sed '/^$/d' | sed 's/[[:space:]]\+$//' > participant_answers.txt

      - name: Create Correct Answers File from Secret
        run: |
          # Retrieve correct answers from GitHub secret and format consistently
          echo "$CORRECT_ANSWERS" | tr -d '\r' | sed '/^$/d' | sed 's/[[:space:]]\+$//' > correct_answers.txt
        env:
          CORRECT_ANSWERS: ${{ secrets.CORRECT_ANSWERS }}

      - name: Print Correct Answers
        run: cat correct_answers.txt

      - name: Print Participant Answers
        run: cat participant_answers.txt

      - name: Compare Answers
        run: |
          echo "Comparing answers..."
          # Check if participant answers match correct answers exactly
          if cmp -s correct_answers.txt participant_answers.txt; then
            echo "Answers correct. Ready to merge."
          else
            echo "Answers incorrect. Auto-merge not allowed."
            exit 1
          fi
